CREATE TABLE `apiKeys` (
	`_id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`service` text NOT NULL,
	`key` text NOT NULL,
	`name` text,
	`isActive` integer DEFAULT true NOT NULL,
	`lastUsed` integer,
	`usageCount` integer DEFAULT 0 NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `backgroundAudio` (
	`_id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`title` text,
	`searchTerm` text,
	`prompt` text,
	`description` text,
	`genre` text,
	`mood` text,
	`tempo` text,
	`instrumental` integer,
	`audioUrl` text,
	`audioFileId` text,
	`volume` integer,
	`duration` integer,
	`loop` integer,
	`generatedAt` integer,
	`generationTimeMs` integer,
	`userId` text NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `channels` (
	`_id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`profileId` text,
	`youtubeChannelId` text,
	`youtubeChannelName` text,
	`youtubeChannelUrl` text,
	`youtubeChannelAvatar` text,
	`youtubeChannelBanner` text,
	`youtubeChannelDescription` text,
	`youtubeChannelSubscriberCount` integer,
	`youtubeChannelVideoCount` integer,
	`youtubeChannelViewCount` integer,
	`youtubeChannelKeywords` text,
	`youtubeChannelTopicCategories` text,
	`youtubeChannelCountry` text,
	`youtubeChannelPublishedAt` integer,
	`youtubeChannelLastUpdated` integer,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`profileId`) REFERENCES `profiles`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `chapters` (
	`_id` text PRIMARY KEY NOT NULL,
	`videoId` text NOT NULL,
	`chapterNumber` integer NOT NULL,
	`title` text,
	`description` text,
	`narrationScript` text,
	`startTime` integer,
	`endTime` integer,
	`audioUrl` text,
	`audioFileId` text,
	`audioDuration` integer,
	`audioGeneratedAt` integer,
	`audioGenerationTimeMs` integer,
	`imagePrompt` text,
	`imageUrl` text,
	`imageFileId` text,
	`imageGeneratedAt` integer,
	`imageGenerationTimeMs` integer,
	`status` text DEFAULT 'draft' NOT NULL,
	`userId` text NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`videoId`) REFERENCES `videos`(`_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `files` (
	`_id` text PRIMARY KEY NOT NULL,
	`filename` text NOT NULL,
	`originalName` text NOT NULL,
	`mimeType` text NOT NULL,
	`size` integer NOT NULL,
	`path` text NOT NULL,
	`publicUrl` text,
	`fileId` text,
	`uploadProvider` text,
	`versionChainId` text,
	`isVersion` integer DEFAULT false NOT NULL,
	`userId` text NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `performanceMetrics` (
	`_id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`operation` text NOT NULL,
	`duration` integer NOT NULL,
	`success` integer NOT NULL,
	`error` text,
	`metadata` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `processEstimates` (
	`_id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`type` text NOT NULL,
	`provider` text,
	`model` text,
	`estimatedDuration` integer,
	`actualDuration` integer,
	`accuracy` real,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `processes` (
	`_id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`priority` integer DEFAULT 0 NOT NULL,
	`userId` text NOT NULL,
	`resourceId` text,
	`groupId` text,
	`weight` integer DEFAULT 1 NOT NULL,
	`estimatedDuration` integer,
	`startedAt` integer,
	`completedAt` integer,
	`failedAt` integer,
	`progress` integer,
	`stage` text,
	`message` text,
	`error` text,
	`result` text,
	`metadata` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `profiles` (
	`_id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`narratorPromptTemplate` text,
	`introScriptTemplate` text,
	`outroScriptTemplate` text,
	`imageStylePrompt` text,
	`imageDescriptionPrompt` text,
	`soundGenerationPrompt` text,
	`musicGenerationPrompt` text,
	`chapterGenerationPrompt` text,
	`advertisingScriptPrompt` text,
	`enableMidstoryCTA` integer DEFAULT true,
	`chapterTransitionPrompt` text,
	`antiAiPrompt` text,
	`imageProvider` text DEFAULT 'huggingface',
	`ttsProvider` text,
	`ttsUseEmotionalTags` integer DEFAULT false,
	`ttsSettings` text,
	`ttsVoice` text,
	`ttsModel` text,
	`videoProvider` text DEFAULT 'google-veo',
	`videoSettings` text,
	`videoStyle` text DEFAULT 'standard',
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `settings` (
	`_id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`narratorPromptTemplate` text,
	`introScriptTemplate` text,
	`outroScriptTemplate` text,
	`imageStylePrompt` text,
	`imageDescriptionPrompt` text,
	`soundGenerationPrompt` text,
	`musicGenerationPrompt` text,
	`chapterGenerationPrompt` text,
	`advertisingScriptPrompt` text,
	`enableMidstoryCTA` integer DEFAULT true,
	`chapterTransitionPrompt` text,
	`antiAiPrompt` text,
	`imageProvider` text DEFAULT 'huggingface',
	`ttsProvider` text,
	`ttsUseEmotionalTags` integer DEFAULT false,
	`ttsSettings` text,
	`ttsVoice` text,
	`ttsModel` text,
	`videoProvider` text DEFAULT 'google-veo',
	`videoSettings` text,
	`videoStyle` text DEFAULT 'standard',
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `usage` (
	`_id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`serviceType` text NOT NULL,
	`provider` text NOT NULL,
	`operation` text NOT NULL,
	`tokens` integer,
	`characters` integer,
	`images` integer,
	`duration` integer,
	`cost` real,
	`currency` text,
	`model` text,
	`metadata` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `users` (
	`_id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL,
	`password` text NOT NULL,
	`firstName` text,
	`lastName` text,
	`avatarUrl` text,
	`role` text DEFAULT 'user' NOT NULL,
	`isActive` integer DEFAULT true NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `videos` (
	`_id` text PRIMARY KEY NOT NULL,
	`subject` text NOT NULL,
	`description` text,
	`length` integer DEFAULT 120 NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`youtubeId` text,
	`generatedVideoUrl` text,
	`generatedVideoFileId` text,
	`videoGeneratedAt` integer,
	`videoRenderTimeMs` integer,
	`previewVideoUrl` text,
	`youtubeTitle` text,
	`youtubeDescription` text,
	`thumbnailUrl` text,
	`thumbnailFileId` text,
	`originalThumbnailUrl` text,
	`originalThumbnailFileId` text,
	`thumbnailDesign` text,
	`thumbnailVariations` text,
	`tags` text DEFAULT '[]',
	`categoryId` text,
	`privacyStatus` text DEFAULT 'unlisted',
	`madeForKids` integer DEFAULT false,
	`profileId` text,
	`channelId` text,
	`introPrompt` text,
	`advertisingPrompt` text,
	`videoStyle` text DEFAULT 'standard',
	`timeline` text,
	`userId` text NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`profileId`) REFERENCES `profiles`(`_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`channelId`) REFERENCES `channels`(`_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`userId`) REFERENCES `users`(`_id`) ON UPDATE no action ON DELETE no action
);
